import { GridSettings } from './grid-settings';

/** @public */
export const enum GridSettingChangeInvalidateType {
    None,
    ViewRender,
    HorizontalViewLayout,
    VerticalViewLayout,
    ViewLayout,
    HorizontalViewLayoutAndScrollDimension,
    VerticalViewLayoutAndScrollDimension,
    ViewLayoutAndScrollDimension,
    Resize,
}

/** @public */
export type GridSettingChangeInvalidateTypes = {
    [key in keyof GridSettings]: GridSettingChangeInvalidateType;
}

/** @public */
export const gridSettingChangeInvalidateTypes: GridSettingChangeInvalidateTypes = {
    addToggleSelectionAreaModifierKey: GridSettingChangeInvalidateType.None,
    addToggleSelectionAreaModifierKeyDoesToggle: GridSettingChangeInvalidateType.None,
    backgroundColor: GridSettingChangeInvalidateType.ViewRender,
    borderWidth: GridSettingChangeInvalidateType.None,
    borderColor: GridSettingChangeInvalidateType.None,
    color: GridSettingChangeInvalidateType.ViewRender,
    columnAutosizingMax: GridSettingChangeInvalidateType.ViewRender,
    columnClip: GridSettingChangeInvalidateType.ViewRender,
    columnMoveDragPossibleCursorName: GridSettingChangeInvalidateType.None,
    columnMoveDragActiveCursorName: GridSettingChangeInvalidateType.None,
    columnResizeDragPossibleCursorName: GridSettingChangeInvalidateType.None,
    columnResizeDragActiveCursorName: GridSettingChangeInvalidateType.None,
    columnSortPossibleCursorName: GridSettingChangeInvalidateType.None,
    columnsReorderable: GridSettingChangeInvalidateType.None,
    columnsReorderableHideable: GridSettingChangeInvalidateType.None,
    defaultRowHeight: GridSettingChangeInvalidateType.ViewLayoutAndScrollDimension,
    defaultColumnAutosizing: GridSettingChangeInvalidateType.None,
    defaultColumnWidth: GridSettingChangeInvalidateType.None,
    defaultUiBehaviorTypeNames: GridSettingChangeInvalidateType.Resize,
    editable: GridSettingChangeInvalidateType.None,
    editOnDoubleClick: GridSettingChangeInvalidateType.None,
    editOnKeydown: GridSettingChangeInvalidateType.None,
    editKey: GridSettingChangeInvalidateType.None,
    editOnFocusCell: GridSettingChangeInvalidateType.None,
    enableContinuousRepaint: GridSettingChangeInvalidateType.ViewRender,
    extendLastSelectionAreaModifierKey: GridSettingChangeInvalidateType.None,
    eventDispatchEnabled: GridSettingChangeInvalidateType.None,
    filterable: GridSettingChangeInvalidateType.None,
    filterBackgroundColor: GridSettingChangeInvalidateType.ViewRender,
    filterBackgroundSelectionColor: GridSettingChangeInvalidateType.ViewRender,
    filterColor: GridSettingChangeInvalidateType.ViewRender,
    filterEditor: GridSettingChangeInvalidateType.ViewRender,
    filterFont: GridSettingChangeInvalidateType.ViewRender,
    filterForegroundSelectionColor: GridSettingChangeInvalidateType.ViewRender,
    filterHalign: GridSettingChangeInvalidateType.ViewRender,
    filterCellPainter: GridSettingChangeInvalidateType.ViewRender,
    fixedColumnCount: GridSettingChangeInvalidateType.HorizontalViewLayoutAndScrollDimension,
    fixedLinesHColor: GridSettingChangeInvalidateType.ViewRender,
    fixedLinesHEdge: GridSettingChangeInvalidateType.VerticalViewLayoutAndScrollDimension,
    fixedLinesHWidth: GridSettingChangeInvalidateType.VerticalViewLayoutAndScrollDimension,
    fixedLinesVColor: GridSettingChangeInvalidateType.ViewRender,
    fixedLinesVEdge: GridSettingChangeInvalidateType.HorizontalViewLayoutAndScrollDimension,
    fixedLinesVWidth: GridSettingChangeInvalidateType.HorizontalViewLayoutAndScrollDimension,
    fixedRowCount: GridSettingChangeInvalidateType.ViewLayoutAndScrollDimension,
    gridRightAligned: GridSettingChangeInvalidateType.ViewLayoutAndScrollDimension,
    gridBorder: GridSettingChangeInvalidateType.Resize,
    gridBorderBottom: GridSettingChangeInvalidateType.Resize,
    gridBorderLeft: GridSettingChangeInvalidateType.Resize,
    gridBorderRight: GridSettingChangeInvalidateType.Resize,
    gridBorderTop: GridSettingChangeInvalidateType.Resize,
    verticalGridLinesVisible: GridSettingChangeInvalidateType.ViewRender,
    gridLinesH: GridSettingChangeInvalidateType.VerticalViewLayoutAndScrollDimension,
    gridLinesHColor: GridSettingChangeInvalidateType.ViewRender,
    gridLinesHWidth: GridSettingChangeInvalidateType.VerticalViewLayoutAndScrollDimension,
    horizontalGridLinesVisible: GridSettingChangeInvalidateType.ViewRender,
    gridLinesV: GridSettingChangeInvalidateType.HorizontalViewLayoutAndScrollDimension,
    gridLinesVColor: GridSettingChangeInvalidateType.ViewRender,
    gridLinesVWidth: GridSettingChangeInvalidateType.HorizontalViewLayoutAndScrollDimension,
    horizontalWheelScrollingAllowed: GridSettingChangeInvalidateType.None,
    horizontalScrollbarClassPrefix: GridSettingChangeInvalidateType.None,
    minimumColumnWidth: GridSettingChangeInvalidateType.ViewLayoutAndScrollDimension,
    maximumColumnWidth: GridSettingChangeInvalidateType.ViewLayoutAndScrollDimension,
    visibleColumnWidthAdjust: GridSettingChangeInvalidateType.ViewLayoutAndScrollDimension,
    mouseRectangleSelection: GridSettingChangeInvalidateType.None,
    mouseColumnSelection: GridSettingChangeInvalidateType.None,
    mouseRowSelection: GridSettingChangeInvalidateType.None,
    multipleSelectionAreas: GridSettingChangeInvalidateType.None,
    primarySelectionAreaType: GridSettingChangeInvalidateType.None,
    repaintImmediately: GridSettingChangeInvalidateType.None,
    repaintFramesPerSecond: GridSettingChangeInvalidateType.None,
    resizeColumnInPlace: GridSettingChangeInvalidateType.None,
    resizedEventDebounceExtendedWhenPossible: GridSettingChangeInvalidateType.None,
    resizedEventDebounceInterval: GridSettingChangeInvalidateType.None,
    rowResize: GridSettingChangeInvalidateType.VerticalViewLayoutAndScrollDimension,
    rowStripes: GridSettingChangeInvalidateType.ViewRender,
    scrollHorizontallySmoothly: GridSettingChangeInvalidateType.HorizontalViewLayoutAndScrollDimension,
    scrollbarHoverOver: GridSettingChangeInvalidateType.None,
    scrollbarHoverOff: GridSettingChangeInvalidateType.None,
    scrollingEnabled: GridSettingChangeInvalidateType.None,
    secondarySelectionAreaTypeSpecifierModifierKey: GridSettingChangeInvalidateType.None,
    secondarySelectionAreaType: GridSettingChangeInvalidateType.None,
    selectionExtendDragActiveCursorName: GridSettingChangeInvalidateType.None,
    selectionRegionOutlineColor: GridSettingChangeInvalidateType.ViewRender,
    selectionRegionOverlayColor: GridSettingChangeInvalidateType.ViewRender,
    showFilterRow: GridSettingChangeInvalidateType.VerticalViewLayoutAndScrollDimension,
    mouseSortOnDoubleClick: GridSettingChangeInvalidateType.None,
    mouseSortable: GridSettingChangeInvalidateType.None,
    useHiDPI: GridSettingChangeInvalidateType.Resize,
    verticalScrollbarClassPrefix: GridSettingChangeInvalidateType.Resize,
    wheelHFactor: GridSettingChangeInvalidateType.None,
    wheelVFactor: GridSettingChangeInvalidateType.None,
};
