import { Rectangle } from '../../types-utils/rectangle';
import { SchemaServer } from '../schema/schema-server';
import { BehavioredColumnSettings } from '../settings/behaviored-column-settings';
import { DataServer } from './data-server';
import { ViewCell } from './view-cell';

/** @public */
export interface CellEditor<BCS extends BehavioredColumnSettings, SC extends SchemaServer.Column<BCS>> {

    // Common properties, methods and events

    /** Indicates if editor can only display data */
    readonly readonly: boolean;

    /** Provide the initial data to the editor. This is done after all events have been subscribed to - so editor can start running */
    open(initialValue: DataServer.ViewValue, valueIsNew: boolean): void;
    /** Close the editor - returns data that was in editor or undefined if cancel specified */
    close(cancel: boolean): DataServer.ViewValue | undefined;

    /** Server data value has changed since being provided to editor or pulled by editor */
    invalidateValue?(): void;

    /** See if the editor wants the keyboard event.  If fromEditor is true, then this editor generated the event in the first place */
    checkConsumeKeyDownEvent(event: KeyboardEvent, fromEditor: boolean): boolean;

    /** Get latest data from data server */
    pullValueEventer?: CellEditor.PullDataEventer;
    /** Save data to data server. Optional. If not supplied then editor is read only */
    pushValueEventer?: CellEditor.PushDataEventer;

    /** Editor can optionally use this eventer to notify Grid that it has completed */
    closedEventer?: CellEditor.ClosedEventer;

    // HTML Element methods and events

    /** Implement if editor paints itself (eg a HTML Input element). If bounds is undefined, then editor is hidden */
    setBounds?(bounds: Rectangle | undefined): void;
    /** Implement if editor can be focused. */
    focus?(): void;
    /** Emits key down events generated by editor */
    keyDownEventer?: CellEditor.KeyDownEventer;

    // Painted Editor properties, methods and events

    // Request keys which would normally close editor and possibly exit a cell
    /** If true, editor wants to handle Tab key instead of grid */
    readonly wantTab?: boolean;
    /** If true, editor wants to handle Return key instead of grid */
    readonly wantReturn?: boolean;
    /** If true, editor wants to handle Escape key instead of grid */
    readonly wantEscape?: boolean;
    /** If true, editor wants to handle Left Arrow key instead of grid */
    readonly wantLeftArrow?: boolean;
    /** If true, editor wants to handle Right Arrow key instead of grid */
    readonly wantRightArrow?: boolean;
    /** If true, editor wants to handle Up Arrow key instead of grid */
    readonly wantUpArrow?: boolean;
    /** If true, editor wants to handle Down Arrow key instead of grid */
    readonly wantDownArrow?: boolean;
    /** If true, editor wants to handle Home key instead of grid */
    readonly wantHome?: boolean;
    /** If true, editor wants to handle End key instead of grid */
    readonly wantEnd?: boolean;

    /** Paint the editor */
    paint?(prefillColor: string | undefined): number | undefined; // Must have same signature as CellPainter.paint()

    /** Implement if editor wants key down events */
    keyDown?(event: KeyboardEvent): void;
    /** Implement if editor wants key up events */
    keyUp?(event: KeyboardEvent): void;

    /** Implement if editor wants mouse click events */
    click?(event: MouseEvent, cell: ViewCell<BCS, SC> | undefined): void;
    /** Implement if editor wants mouse double click events */
    dblClick?(event: MouseEvent, cell: ViewCell<BCS, SC> | undefined): void;
    /** Implement if editor wants mouse down events */
    mouseDown?(event: MouseEvent, cell: ViewCell<BCS, SC> | undefined): void;
    /** Implement if editor wants mouse up events */
    mouseUp?(event: MouseEvent, cell: ViewCell<BCS, SC> | undefined): void;
    /** Implement if editor wants wheel move events */
    wheelMove?(event: WheelEvent, cell: ViewCell<BCS, SC> | undefined): void;
}

/** @public */
export namespace CellEditor {
    export type PullDataEventer = (this: void) => DataServer.ViewValue;
    export type PushDataEventer = (this: void, value: DataServer.ViewValue) => void;
    export type ClosedEventer = (this: void, value: DataServer.ViewValue | undefined) => void;
    export type KeyDownEventer = (this: void, event: KeyboardEvent) => void;
}
